name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run all the tests
        run: go test -v ./...

      - name: Build to a binary
        run: go build -v ./...

      - name: Build the docker image
        run: ./build.sh
        shell: bash


